"""Presentation layer turning analysis reports into display-ready models."""

from __future__ import annotations

from .builders import (
    DashboardBuilder,
    EchoReportBuilder,
    build_dashboard_view,
    build_echo_report_view,
)
from .formatters import (
    format_active_period,
    format_average,
    format_count,
    format_duration,
    format_hour,
    format_length_bucket,
    format_percent,
    format_weekday,
)
from .echo_serializer import (
    ECHO_REPORT_SCHEMA_VERSION,
    echo_report_to_dict,
    export_echo_report_html,
    export_echo_report_json,
)
from .expression_assets import (
    expression_asset_data_uri,
    resolve_wechat_asset_key,
    wechat_asset_index,
)
from .models import (
    ChartData,
    ChartKind,
    ChartPoint,
    ChartSeries,
    ConversationCard,
    DashboardView,
    EchoConversationSession,
    EchoConversationSessions,
    EchoExpressionCombination,
    EchoExpressionCombinationMember,
    EchoExpressionCulture,
    EchoExpressionHabits,
    EchoExpressionItem,
    EchoLanguageMember,
    EchoLanguageProfile,
    EchoMemberExpression,
    EchoMemberCard,
    EchoReportView,
    EchoSharedWord,
    MetricCard,
    UserCard,
)


__all__ = [
    "ChartData",
    "ChartKind",
    "ChartPoint",
    "ChartSeries",
    "ConversationCard",
    "DashboardBuilder",
    "DashboardView",
    "EchoMemberCard",
    "EchoConversationSession",
    "EchoConversationSessions",
    "EchoExpressionCombination",
    "EchoExpressionCombinationMember",
    "EchoExpressionCulture",
    "EchoExpressionHabits",
    "EchoExpressionItem",
    "EchoLanguageMember",
    "EchoLanguageProfile",
    "EchoMemberExpression",
    "EchoReportBuilder",
    "EchoReportView",
    "EchoSharedWord",
    "ECHO_REPORT_SCHEMA_VERSION",
    "MetricCard",
    "UserCard",
    "build_dashboard_view",
    "build_echo_report_view",
    "echo_report_to_dict",
    "export_echo_report_html",
    "export_echo_report_json",
    "expression_asset_data_uri",
    "resolve_wechat_asset_key",
    "wechat_asset_index",
    "format_active_period",
    "format_average",
    "format_count",
    "format_duration",
    "format_hour",
    "format_length_bucket",
    "format_percent",
    "format_weekday",
]
