"""Talk to a locally running QQChatExporter (QCE) HTTP service.

This module is a thin client. It starts nothing, reads no QQ database, and does
not convert chat payloads; turning an exported JSON file into
:class:`~qq_chat_analyzer.message.ChatMessage` objects remains the job of
``qq_chat_exporter_adapter``.

Surface used (confirmed by reading the QCE Rust server sources):

* ``GET  /health``                - public liveness probe
* ``GET  /api/groups``            - paginated group list
* ``POST /api/messages/export``   - register an export task, returns immediately
* ``GET  /api/tasks/{taskId}``    - poll task state

Every response is wrapped as ``{"success": bool, "data": ..., "requestId": ...}``.
Authentication uses ``Authorization: Bearer <token>``; the token is generated by
the service and persisted in ``security.json`` under the QCE config directory.

Task ``status`` is a bare string, one of ``running``, ``completed``, ``failed``
or ``cancelled``. Only ``completed`` guarantees a usable ``filePath``, so
``progress`` is treated as display-only and never used as a completion signal.
"""

from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.parse
import urllib.request
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable


DEFAULT_BASE_URL = "http://127.0.0.1:40653"
DEFAULT_TIMEOUT_SECONDS = 30
DEFAULT_EXPORT_TIMEOUT_SECONDS = 900
DEFAULT_POLL_INTERVAL_SECONDS = 2.0
DEFAULT_GROUP_LIMIT = 200
GROUP_CHAT_TYPE = 2
SECURITY_FILE_NAME = "security.json"
QCE_DIR_NAME = ".qq-chat-exporter"

STATUS_RUNNING = "running"
STATUS_COMPLETED = "completed"
STATUS_FAILED = "failed"
STATUS_CANCELLED = "cancelled"
TERMINAL_STATUSES = frozenset({STATUS_COMPLETED, STATUS_FAILED, STATUS_CANCELLED})


class QQChatExporterError(Exception):
    """Base error for QCE service integration failures."""

    code = "qce_error"
    public_message = "QQ 数据源操作失败，请稍后重试。"

    def __init__(self, public_message: str | None = None) -> None:
        self.public_message = public_message or type(self).public_message
        super().__init__(self.public_message)


class ServiceUnavailable(QQChatExporterError):
    """Raised when the QCE service cannot be reached at all."""

    code = "service_unavailable"
    public_message = (
        "未检测到可用的 QQ 数据源，"
        "请确认 QQ 已登录后重试。"
    )


class TokenUnavailable(QQChatExporterError):
    """Raised when no access token can be resolved."""

    code = "token_unavailable"
    public_message = (
        "QQ 需要先完成登录授权，"
        "请确认 QQ 已登录后重试。"
    )


class RequestFailed(QQChatExporterError):
    """Raised when the service answers with an error envelope or bad status."""

    code = "request_failed"
    public_message = "QQ 数据源请求失败，请稍后重试。"


class TaskNotFound(QQChatExporterError):
    """Raised when a polled task no longer exists on the service."""

    code = "task_not_found"
    public_message = (
        "\u5bfc\u51fa\u4efb\u52a1\u5df2\u4e0d\u5b58\u5728\uff0c\u53ef\u80fd\u5df2\u88ab\u5220\u9664\u3002"
    )


class ExportTaskLimitReached(QQChatExporterError):
    """Raised when the service refuses a new task because too many are running."""

    code = "export_task_limit_reached"
    public_message = "QQ 导出任务已达上限，请稍后重试。"


class ExportTaskFailed(QQChatExporterError):
    """Raised when the export task reaches the ``failed`` state."""

    code = "export_task_failed"
    public_message = "QQ \u804a\u5929\u8bb0\u5f55\u5bfc\u51fa\u5931\u8d25\u3002"

    def __init__(self, error: str | None = None) -> None:
        self.error = error or ""
        message = type(self).public_message
        if self.error:
            message = f"{message}\uff08{self.error}\uff09"
        super().__init__(message)


class ExportTaskCancelled(QQChatExporterError):
    """Raised when the export task reaches the ``cancelled`` state."""

    code = "export_task_cancelled"
    public_message = "QQ \u804a\u5929\u8bb0\u5f55\u5bfc\u51fa\u5df2\u88ab\u53d6\u6d88\u3002"


class ExportTimeout(QQChatExporterError):
    """Raised when the task does not reach a terminal state within the budget."""

    code = "export_timeout"
    public_message = (
        "QQ \u804a\u5929\u8bb0\u5f55\u5bfc\u51fa\u8d85\u65f6\uff0c"
        "\u8bf7\u7a0d\u540e\u91cd\u8bd5\u6216\u7f29\u5c0f\u65f6\u95f4\u8303\u56f4\u3002"
    )


@dataclass(frozen=True, slots=True)
class ServiceHealth:
    """Privacy-safe snapshot of ``GET /health``."""

    available: bool
    status: str = ""
    version: str = ""


@dataclass(frozen=True, slots=True)
class ExportGroup:
    """Group descriptor from ``GET /api/groups``."""

    group_code: str
    group_name: str
    member_count: int | None = None


@dataclass(frozen=True, slots=True)
class ExportTask:
    """Snapshot of an export task."""

    task_id: str
    status: str
    progress: int = 0
    message_count: int | None = None
    session_name: str = ""
    chat_type: int | None = None
    peer_uid: str = ""
    progress_message: str = ""
    created_at: str = ""
    completed_at: str = ""
    download_url: str = ""
    file_path: str = ""
    file_name: str = ""
    error: str = ""
    raw: Mapping[str, Any] = field(default_factory=dict)

    @property
    def is_terminal(self) -> bool:
        return self.status in TERMINAL_STATUSES


def resolve_security_candidates() -> tuple[Path, ...]:
    """Return ``security.json`` candidate paths in lookup order.

    ``QCE_CONFIG_DIR`` always wins when set. The v6.x runtime stores its
    token at ``%USERPROFILE%\\.qq-chat-exporter\\security.json``, so that
    user-home path comes first; the older desktop install location under
    ``%LOCALAPPDATA%\\QQChatExporter\\.qce-config`` remains a fallback.
    """
    override = os.environ.get("QCE_CONFIG_DIR", "").strip()
    if override:
        return (Path(override) / SECURITY_FILE_NAME,)

    candidates: list[Path] = []
    candidates.append(Path.home() / QCE_DIR_NAME / SECURITY_FILE_NAME)
    if os.name == "nt":
        local_app_data = os.environ.get("LOCALAPPDATA", "").strip()
        if local_app_data:
            candidates.append(
                Path(local_app_data)
                / "QQChatExporter"
                / ".qce-config"
                / SECURITY_FILE_NAME
            )
    return tuple(candidates)


def resolve_security_path() -> Path:
    """Return the highest-priority ``security.json`` location."""
    return resolve_security_candidates()[0]


def read_token(path: Path | None = None) -> str | None:
    """Read the access token from the first usable ``security.json``.

    An explicit ``path`` is checked first, then the standard candidate
    locations. The bundled runtime points at its own config directory which
    may be empty on first use, so falling back to the user-profile token file
    keeps ``%USERPROFILE%\\.qq-chat-exporter\\security.json`` working.
    """
    targets = list(resolve_security_candidates())
    if path is not None:
        targets.insert(0, Path(path))
    for target in targets:
        token = _read_token_file(target)
        if token:
            return token
    return None


def _read_token_file(target: Path) -> str | None:
    """Read one ``security.json`` file without leaking its value into logs."""
    try:
        raw = target.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None

    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        return None
    if not isinstance(payload, Mapping):
        return None

    for key in ("accessToken", "token", "apiToken"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return None


class QQChatExporterProvider:
    """HTTP client for a locally running QCE service."""

    def __init__(
        self,
        base_url: str = DEFAULT_BASE_URL,
        token: str | None = None,
        timeout: int = DEFAULT_TIMEOUT_SECONDS,
        security_path: Path | None = None,
        transport: Callable[[str, str, bytes | None, Mapping[str, str], int], tuple[int, str]]
        | None = None,
        sleep: Callable[[float], None] | None = None,
        monotonic: Callable[[], float] | None = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        self._token = token
        self._timeout = timeout
        self._security_path = security_path
        self._transport = transport or _urllib_transport
        self._sleep = sleep or time.sleep
        self._monotonic = monotonic or time.monotonic

    # ------------------------------------------------------------------ probing

    def health_check(self) -> ServiceHealth:
        """Probe ``/health``. Never raises for an unreachable service."""
        try:
            data = self._request("GET", "/health", authenticated=False)
        except QQChatExporterError:
            return ServiceHealth(available=False)

        if isinstance(data, Mapping):
            return ServiceHealth(
                available=True,
                status=str(data.get("status") or ""),
                version=str(data.get("version") or ""),
            )
        return ServiceHealth(available=True)

    def is_available(self) -> bool:
        return self.health_check().available

    def resolve_token(self) -> str:
        """Return the token, reading ``security.json`` on first use."""
        if self._token:
            return self._token
        token = read_token(self._security_path)
        if not token:
            raise TokenUnavailable()
        self._token = token
        return token

    # ------------------------------------------------------------------ tasks

    def list_tasks(self) -> list[ExportTask]:
        """Return the QCE export task list as :class:`ExportTask` snapshots."""
        data = self._request("GET", "/api/tasks")
        rows: Any = []
        if isinstance(data, Mapping):
            rows = data.get("tasks")
        if not isinstance(rows, list):
            return []

        tasks: list[ExportTask] = []
        for row in rows:
            if not isinstance(row, Mapping):
                continue
            task = _build_task(row)
            if task.task_id:
                tasks.append(task)
        return tasks

    # ------------------------------------------------------------------ listing

    def list_groups(
        self,
        page: int = 1,
        limit: int = DEFAULT_GROUP_LIMIT,
        force_refresh: bool = False,
    ) -> list[ExportGroup]:
        """Return one page of groups."""
        query = {"page": str(page), "limit": str(limit)}
        if force_refresh:
            query["forceRefresh"] = "true"
        data = self._request("GET", "/api/groups", query=query)

        rows: Any = []
        if isinstance(data, Mapping):
            rows = data.get("groups")
        if not isinstance(rows, list):
            return []

        groups: list[ExportGroup] = []
        for row in rows:
            if not isinstance(row, Mapping):
                continue
            code = _clean_str(row.get("groupCode"))
            if not code:
                continue
            groups.append(
                ExportGroup(
                    group_code=code,
                    group_name=_clean_str(row.get("groupName")),
                    member_count=_optional_int(row.get("memberCount")),
                )
            )
        return groups

    # ------------------------------------------------------------------ exports

    def create_export_task(
        self,
        group_code: str,
        start_time: Any = None,
        end_time: Any = None,
        session_name: str | None = None,
        output_dir: str | None = None,
    ) -> ExportTask:
        """Register a group JSON export task and return its initial snapshot."""
        code = _clean_str(group_code)
        if not code:
            raise RequestFailed(
                "\u7f3a\u5c11\u7fa4\u53f7\uff0c\u65e0\u6cd5\u521b\u5efa\u5bfc\u51fa\u4efb\u52a1\u3002"
            )

        body: dict[str, Any] = {
            "peer": {"chatType": GROUP_CHAT_TYPE, "peerUid": code},
            "format": "JSON",
        }
        filter_block: dict[str, Any] = {}
        if start_time is not None:
            filter_block["startTime"] = start_time
        if end_time is not None:
            filter_block["endTime"] = end_time
        if filter_block:
            body["filter"] = filter_block
        if session_name:
            body["sessionName"] = session_name
        if output_dir:
            body["options"] = {"outputDir": output_dir}

        data = self._request("POST", "/api/messages/export", body=body)
        if not isinstance(data, Mapping):
            raise RequestFailed()
        task = _build_task(data)
        if not task.task_id:
            raise RequestFailed()
        return task

    def get_export_task(self, task_id: str) -> ExportTask:
        """Fetch a single task snapshot."""
        identifier = urllib.parse.quote(_clean_str(task_id), safe="")
        data = self._request("GET", f"/api/tasks/{identifier}")
        if not isinstance(data, Mapping):
            raise RequestFailed()
        return _build_task(data)

    def wait_export_task(
        self,
        task_id: str,
        timeout: float = DEFAULT_EXPORT_TIMEOUT_SECONDS,
        poll_interval: float = DEFAULT_POLL_INTERVAL_SECONDS,
    ) -> Path:
        """Poll until the task settles and return the exported JSON path.

        Terminal states are decided by ``status`` alone. ``progress`` is not a
        completion signal: a failed task keeps whatever progress it had when it
        broke.
        """
        deadline = self._monotonic() + timeout
        while True:
            task = self.get_export_task(task_id)

            if task.status == STATUS_COMPLETED:
                if not task.file_path:
                    raise ExportTaskFailed(
                        "\u5bfc\u51fa\u5df2\u5b8c\u6210\u4f46\u672a\u8fd4\u56de\u6587\u4ef6\u8def\u5f84\u3002"
                    )
                return Path(task.file_path)
            if task.status == STATUS_FAILED:
                raise ExportTaskFailed(task.error)
            if task.status == STATUS_CANCELLED:
                raise ExportTaskCancelled()

            if self._monotonic() >= deadline:
                raise ExportTimeout()
            self._sleep(poll_interval)

    def export_group_json(
        self,
        group_code: str,
        start_time: Any = None,
        end_time: Any = None,
        timeout: float = DEFAULT_EXPORT_TIMEOUT_SECONDS,
        poll_interval: float = DEFAULT_POLL_INTERVAL_SECONDS,
    ) -> Path:
        """Convenience wrapper: create a task, then wait for its output file."""
        task = self.create_export_task(
            group_code,
            start_time=start_time,
            end_time=end_time,
        )
        return self.wait_export_task(
            task.task_id,
            timeout=timeout,
            poll_interval=poll_interval,
        )

    # ---------------------------------------------------------------- internals

    def _request(
        self,
        method: str,
        path: str,
        query: Mapping[str, str] | None = None,
        body: Mapping[str, Any] | None = None,
        authenticated: bool = True,
    ) -> Any:
        url = f"{self._base_url}{path}"
        if query:
            url = f"{url}?{urllib.parse.urlencode(query)}"

        headers = {"Accept": "application/json"}
        payload: bytes | None = None
        if body is not None:
            payload = json.dumps(body, ensure_ascii=False).encode("utf-8")
            headers["Content-Type"] = "application/json"
        if authenticated:
            headers["Authorization"] = f"Bearer {self.resolve_token()}"

        try:
            status, text = self._transport(method, url, payload, headers, self._timeout)
        except (urllib.error.URLError, OSError, TimeoutError) as error:
            raise ServiceUnavailable() from error

        return _unwrap(status, text)


def _urllib_transport(
    method: str,
    url: str,
    payload: bytes | None,
    headers: Mapping[str, str],
    timeout: int,
) -> tuple[int, str]:
    """Perform one HTTP call against the local QCE service."""
    if not url.startswith(("http://127.0.0.1", "http://localhost", "http://[::1]")):
        raise ServiceUnavailable(
            "仅支持连接本机 QQ 数据源。"
        )

    request = urllib.request.Request(url, data=payload, method=method)
    for key, value in headers.items():
        request.add_header(key, value)

    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:  # noqa: S310
            body = response.read().decode("utf-8", errors="replace")
            return int(response.status), body
    except urllib.error.HTTPError as error:
        body = ""
        try:
            body = error.read().decode("utf-8", errors="replace")
        except Exception:  # pragma: no cover - best effort on broken streams
            body = ""
        return int(error.code), body


def _unwrap(status: int, text: str) -> Any:
    """Validate the ``{success, data}`` envelope and surface typed errors."""
    payload: Any = None
    if text:
        try:
            payload = json.loads(text)
        except json.JSONDecodeError:
            payload = None

    envelope = payload if isinstance(payload, Mapping) else {}
    error_code = _clean_str(envelope.get("code")) or _extract_error_code(envelope)
    message = _extract_error_message(envelope)

    if error_code == "TASK_NOT_FOUND" or status == 404:
        raise TaskNotFound()
    if error_code == "EXPORT_TASK_LIMIT_REACHED" or status == 429:
        raise ExportTaskLimitReached()
    if status in (401, 403):
        raise TokenUnavailable()
    if status >= 500:
        raise RequestFailed()
    if status >= 400:
        raise RequestFailed(message or None)

    if envelope.get("success") is False:
        raise RequestFailed(message or None)
    if not envelope:
        raise RequestFailed()
    return envelope.get("data")


def _extract_error_code(envelope: Mapping[str, Any]) -> str:
    block = envelope.get("error")
    if isinstance(block, Mapping):
        return _clean_str(block.get("code"))
    return ""


def _extract_error_message(envelope: Mapping[str, Any]) -> str:
    block = envelope.get("error")
    if isinstance(block, Mapping):
        text = _clean_str(block.get("message"))
        if text:
            return text
    if isinstance(block, str):
        return block.strip()
    return _clean_str(envelope.get("message"))


def _build_task(data: Mapping[str, Any]) -> ExportTask:
    task_id = _clean_str(data.get("taskId")) or _clean_str(data.get("id"))
    peer = data.get("peer")
    peer_fields = peer if isinstance(peer, Mapping) else {}
    return ExportTask(
        task_id=task_id,
        status=_clean_str(data.get("status")),
        progress=_optional_int(data.get("progress")) or 0,
        message_count=_optional_int(data.get("messageCount")),
        session_name=(
            _clean_str(data.get("sessionName"))
            or _clean_str(data.get("chatName"))
        ),
        chat_type=_optional_int(peer_fields.get("chatType")),
        peer_uid=_clean_str(peer_fields.get("peerUid")),
        progress_message=(
            _clean_str(data.get("progressMessage"))
            or _clean_str(data.get("message"))
        ),
        created_at=_clean_str(data.get("createdAt")),
        completed_at=_clean_str(data.get("completedAt")),
        download_url=_clean_str(data.get("downloadUrl")),
        file_path=_clean_str(data.get("filePath")),
        file_name=_clean_str(data.get("fileName")),
        error=_extract_task_error(data),
        raw=dict(data),
    )


def _extract_task_error(data: Mapping[str, Any]) -> str:
    value = data.get("error")
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, Mapping):
        return _clean_str(value.get("message"))
    return ""


def _clean_str(value: Any) -> str:
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    return ""


def _optional_int(value: Any) -> int | None:
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    if isinstance(value, str):
        text = value.strip()
        if text.lstrip("-").isdigit():
            return int(text)
    return None
