"""Echo release version from installed metadata generated by pyproject.toml.

The desktop build copies this metadata after verifying the release version.
There is deliberately no hard-coded fallback for a missing installation.
"""

from importlib.metadata import version


APP_VERSION = version("qq-chat-analyzer")
